name: CI/CD to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Archive project
      run: zip -r app.zip . -x "*.git*" "__pycache__/*"

    - name: Copy to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "app.zip"
        target: "/home/${{ secrets.EC2_USER }}/app"

    - name: Deploy on EC2
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        
        script: |
          cd /home/${{ secrets.EC2_USER }}/app
          unzip -o app.zip
        
          aws s3 cp s3://${{ secrets.S3_NAME }}/${{ secrets.S3_TOKEN_NAME }} ./s3_token.txt
        
          echo "CHECK FILE:"
          ls -la

          # ✅ Установка AWS CLI (если нет)
          sudo apt update -y
          sudo apt install -y awscli

          # ✅ Конфигурация AWS
          aws configure set aws_access_key_id ${{ secrets.IAM_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.IAM_SECRET_KEY }}
          aws configure set default.region ${{ secrets.S3_REGION }}

          # ✅ СКАЧИВАЕМ файл из S3
          aws s3 cp s3://${{ secrets.S3_NAME }}/${{ secrets.S3_TOKEN_NAME }} ./s3_token.txt

          # ✅ Docker build уже с файлом
          sudo docker stop vin_bot || true
          sudo docker rm vin_bot || true

          sudo docker build -t vin_bot .

          sudo docker run -d --name vin_bot vin_bot
